Update questions.json
Dearest Maintainer,

I checked this answer and corrected it. I changed the code and question because there was two correct answers.

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d69639f3332f561274c943ea2581c301
```
fn get_value(x: u32) {
x + 5
}

fn main() {
println!("{}", get_value(10));
}
```

```
   Compiling playground v0.0.1 (/playground)
error[E0308]: mismatched types
 --> src/main.rs:2:1
  |
1 | fn get_value(x: u32) {
  |                      - help: try adding a return type: `-> u32`
2 | x + 5
  | ^^^^^ expected `()`, found `u32`

error[E0277]: `()` doesn't implement `std::fmt::Display`
 --> src/main.rs:6:16
  |
6 | println!("{}", get_value(10));
  |                ^^^^^^^^^^^^^ `()` cannot be formatted with the default formatter
  |
  = help: the trait `std::fmt::Display` is not implemented for `()`
  = note: in format strings you may be able to use `{:?}` (or {:#?} for pretty-print) instead
  = note: required by `std::fmt::Display::fmt`
  = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

Thanks. It is fun.
Becker